In [87]:
import tensorflow.compat.v1 as tf

In [24]:
frase = tf.constant('Ola, mundo!')

#with tf.Session() as sess:
#    rodar = sess.run(frase)


print(tf.Session().run(frase))

b'Ola, mundo!'


In [20]:
#variaveis sozinhas sao tensores, só recebem valores quando pedir para rodar dentro do session do tf
print(frase)

Tensor("Const_2:0", shape=(), dtype=string)


In [22]:
#caso queira imporimir com variaveis
frase = tf.constant('Ola, mundo!')

with tf.Session() as sess:
    rodar = sess.run(frase)
    
print(rodar)

b'Ola, mundo!'


In [28]:
#Aula grafos
a = tf.constant(5)
b = tf.constant(3)
c = tf.constant(2)

d = tf.multiply(a,b)
e = tf.add(b,c)
f = tf.subtract(d,e)

sess = tf.Session()
saida = sess.run(f)
sess.close()

In [30]:
print(saida)

10


In [32]:
#Aula tipo de dados
a = tf.constant(2) #1x1
b = tf.constant([3,1,5,8,6]) #1xn
c = tf.constant([[2,0,4], [3,5,7]]) #nxn

# Nos exemplos acima, a é um tensor 0-dimensional (escalar), b é 1-dimensional (vetor) e c é 2-dimensional (matriz)

sess = tf.Session()
saida = sess.run(c)
sess.close()

In [34]:
import numpy as np
a1 = np.array(2)
b1 = np.array([3,1,5,8,6])
c1 = np.array([[2,4,0], [3,5,7]])

In [36]:
print(c.shape)

(2, 3)


In [38]:
print(c1.shape)

(2, 3)


In [44]:
const = tf.constant(4, dtype=tf.float64)

In [42]:
print(const)

Tensor("Const_11:0", shape=(), dtype=float32)


In [46]:
#Aula matrizes

A = tf.constant([[1,2,3],[4,5,6]])
B = tf.constant([[0,0],[1,0],[0,1]])

In [52]:
print(tf.Session().run(B))

[[0 0]
 [1 0]
 [0 1]]


In [54]:
resultado = tf.matmul(A,B)

In [56]:
print(tf.Session().run(resultado))

[[2 3]
 [5 6]]


In [62]:
x = tf.constant([0,1,0])
#Seria impossivel calcular o X com A pois ele nao possui o tanto de coluna necessaria! como resolver isso:
# A funcao expand expande eixo vertical
x = tf.expand_dims(x,1)

In [64]:
print(x.shape)

(3, 1)


In [68]:
resultado2 = tf.matmul(A,x)

In [70]:
print(tf.Session().run(resultado2))

[[2]
 [5]]


In [74]:
#Inverter linhas pelas colunas
transposta = tf.transpose(A)

In [78]:
print(tf.Session().run(A))

[[1 2 3]
 [4 5 6]]


In [80]:
print(tf.Session().run(transposta))

[[1 4]
 [2 5]
 [3 6]]


In [89]:
#Aula variavel
variavel = tf.Variable(2)

In [95]:
#para rodar variavel precisamos iniciar elas, diferente de constantes
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    rodar = sess.run(variavel)
print(rodar)

2


In [97]:
matriz = tf.random_normal((3,5),0,1) #(shape, média, desvio_padrao)

In [101]:
variavel2 = tf.Variable(matriz)

In [103]:
print(matriz)

Tensor("random_normal:0", shape=(3, 5), dtype=float32)


In [105]:
print(variavel2)

<tf.Variable 'Variable_3:0' shape=(3, 5) dtype=float32_ref>


In [119]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    rodar = sess.run(variavel2)
print(rodar)

[[-1.5682727  -1.4439967  -0.1337449  -0.9026132  -1.9650942 ]
 [ 0.8756103   0.816173    0.49905542 -1.0546645  -0.372192  ]
 [ 0.10473226  0.7127403   1.8746604  -0.2172141   0.40051785]]


In [175]:
#aula placeholders

import tensorflow as tf
import numpy as np

dados_x = np.random.randn(4,8)   # cria matriz de 4 linhas e 8 colunas com números aleatórios

dados_w = np.random.randn(8,2)   # cria matriz de 8 linhas e 2 colunas com números aleatórios

b = tf.random.normal((4,2),0,1, tf.float64)   # cria matriz (tensor) de 4 linhas e 2 colunas com números aleatórios

operacao = tf.matmul(dados_x, dados_w) + b
maximo = tf.math.reduce_max(operacao) # encontra o maior valor da matriz operacao

tf.print(operacao)
tf.print(maximo)

<tf.Operation 'PrintV2_8' type=PrintV2>

In [155]:
with tf.compat.v1.Session() as sess:
    
    x1 = np.random.randn(4,8)
    w1 = np.random.randn(8,2)
    
    x2 = np.random.randn(4,8)
    w2 = np.random.randn(8,2)
    
    x3 = np.random.randn(4,8)
    w3 = np.random.randn(8,2)
    
    x4 = np.random.randn(4,8)
    w4 = np.random.randn(8,2)
    
    x5 = np.random.randn(4,8)
    w5 = np.random.randn(8,2)
    
    lista_x = [x1, x2, x3, x4, x5]
    lista_w = [w1, w2, w3, w4, w5]
    lista_saida = []
    
    b = tf.compat.v1.random_normal((4,2),0,1)
    
    x = tf.compat.v1.placeholder(tf.float32, shape=(4,8))
    w = tf.compat.v1.placeholder(tf.float32, shape=(8,2))
    
    operacao = tf.matmul(x, w) + b

    maximo = tf.reduce_max(operacao)
    
    for i in range(5):
        saida = sess.run(maximo, feed_dict={x: lista_x[i], w: lista_w[i]})
        lista_saida.append(saida)
    
    print(lista_saida)



[2.8121097, 6.233085, 4.3498735, 3.710597, 1.8206812]


In [173]:
#Aula TensorBoard
#Criar o primeiro grafo
a = tf.constant(2, dtype=tf.float32, name='tensor_a')
b = tf.constant(3, dtype=tf.float32, name='tensor_b')
c = tf.add(a, b)

with tf.compat.v1.Session() as sess:
    writer = tf.compat.v1.summary.FileWriter('C:/Users/victo/Documents/estudoTF/grafo1', sess.graph)
    saida = sess.run(c)
print(saida)

5.0
